require "rainbow"

require "computering/version"
require "computering/config"
require "computering/dsl"
require "computering/dsl/text"
require "computering/dsl/timer"
require "computering/dsl/headline"
require "computering/dsl/quote"
require "computering/dsl/list"
require "computering/dsl/link"
require "computering/dsl/command"
require "computering/dsl/spec"
require "computering/dsl/code"
require "computering/code_parser"
require "computering/container"
require "computering/cmd"
