require "rainbow"

require "computering/version"
require "computering/config"
require "computering/dsl"
require "computering/dsl/text"
require "computering/dsl/command"
require "computering/dsl/headline"
require "computering/dsl/link"
require "computering/cmd"
